# name: Express CI/CD

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Login to the server and run command
#         env:
#           SSH_HOST: ${{ secrets.SSH_HOST }}
#           SSH_USER: ${{ secrets.SSH_USER }}
#           SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#         run: |
#           echo "$SSH_PRIVATE_KEY" > key.pem
#           chmod 600 key.pem
#           ssh -i key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "ls"
#           rm -f key.pem

name: CICD

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy repository
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GITHUB_REPO: ${{ github.repository }}
          TARGET_DIR: "/myapp"
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem
          
          REPO_URL="git@github.com:${GITHUB_REPO}.git"
          
          ssh -i key.pem -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << 'EOF'
            # Create target directory if it doesn't exist
            mkdir -p "$TARGET_DIR"
            
            # Check if repository exists
            if [ -d "$TARGET_DIR/.git" ]; then
              echo "Updating existing repository..."
              cd "$TARGET_DIR"
              git remote set-url origin "$REPO_URL"
              git fetch origin
              git reset --hard origin/main
            else
              echo "Cloning repository..."
              git clone "$REPO_URL" "$TARGET_DIR"
            fi
            
            # Verify synchronization
            echo "Repository synchronized to:"
            cd "$TARGET_DIR" && git log -1 --oneline
          EOF
          
          rm -f key.pem