name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Application to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > key.pem
          chmod 600 key.pem

          # Dynamically resolve repo name and branch on GitHub runner
          REPO="${{ github.repository }}"        
          BRANCH="${{ github.ref_name }}"       
          APP_NAME=$(basename "$REPO")

          echo "▶ Repo: $REPO"
          echo "▶ Branch: $BRANCH"
          echo "▶ App name: $APP_NAME"

          # SSH and run deploy
          ssh -i key.pem -o StrictHostKeyChecking=no "$SSH_USER@$SSH_HOST" <<EOF
            set -e

            APP_DIR="\$HOME/$APP_NAME"
            REPO_URL="https://github.com/$REPO.git"

            echo "▶ Using APP_DIR: \$APP_DIR"
            if [ ! -d "\$APP_DIR/.git" ]; then
              echo "▶ Cloning repository \$REPO_URL..."
              git clone -b "$BRANCH" "\$REPO_URL" "\$APP_DIR"
            else
              echo "▶ Pulling latest from branch $BRANCH..."
              cd "\$APP_DIR"
              git pull origin "$BRANCH"
            fi

            echo "▶ Making deploy.sh executable..."
            chmod +x "\$APP_DIR/deploy.sh"

            echo "▶ Running deploy.sh inside \$APP_DIR"
            bash "\$APP_DIR/deploy.sh"

            echo "✅ Deployment completed via deploy.sh"
          EOF

          rm -f key.pem

